language: php
php:
- 5.6
- 7.0
before_script:
- cp .env.travis .env
- mysql -e 'create database homestead_test;'
- composer self-update
- composer install --no-interaction
script:
- vendor/bin/phpunit
deploy:
  provider: heroku
  api_key:
    secure: ai4dVGQF7Cxzz+dQfSim1KbT1GaieAqPuc7BG6AdFwqXQIcDhS5rEZTpnmBi60+37cvg0HVFc2I6AhU8PlR4HWRNm8v6ICoqbMdynC8AMMmDNcfsktKnKvo+20Ha7JXDXWVZvR9MruNF+7TTsueizmEc1hb6CaVROd8Ef2sUYcacJzyZ2KdwG2wEy3gvqHbxhA7yixG315AnkgqGWOw3bciFQxLi3X2IBuY7Iy9cUMYtmX+6RmznW3+y6YfBGZWNP5pXvv5wl2spfmFcOEp6cjLYrSnRIDzBdfbMo1NbmLsq6JjMKVPqgtGohO3Pm/zx3h+uIiSJHRV86pHpk8ZAmfleelcv0Pw822adV6eye/mU8ImNUb0bMLSWRP8XrR3zeYQjmNOiI5InSr8CFG7EALGeSS6GHGUEkCFCta82tsRDJY8gbMrBsjbBMiyyZ0BY3SxtWzFvdHlbW1DdaOcnDTTqRHgvyxpa238PW76GVygPG6e1ccYxoictXkNoUTtRKQycDojrNVi4bFerWollKOEycwO3oz6wq35w72rc6bVIW05QD+wfaeI+EtzWQjjwyzCkJ42iM9rS69y9wGzLso6327s7ozg3jYpTM9s5K5ICK+sqs+myrLS0ikLoNr4tIGZZwFcMsYgTSI+FAVrzY2mnTk4wjFTaTqALJKqmJvw=
  app: pickems-api
  on:
    repo: kcin1018/pickems-api
