language: php
php:
- 5.6
- 7.0
before_script:
- cp .env.travis .env
- mysql -e 'create database homestead_test;'
- composer self-update
- composer install --no-interaction
script:
- vendor/bin/phpunit
deploy:
  provider: heroku
  api_key:
    secure: XpBI4KwILFQxDh74Jq+SlwkZvW6nQGcN40Eo6BFhaLBfimlQNFzNYOqGGH2yuAGHBUsADB5BEPGBT9iW1Cy7O8W8vviOxr3CTO15SGWvzW51ijBRd+8bLPuv+kdzQoH/c12BDdcfBsPVODhhJ3pDO3AX8/1PwqhDexz7pr2I5bDr+DevShyW+wNyL9td9La4wItzmp/NRDg8h0t36Hg4hnVT9qV/76kZ0KoX/6RbL9ap1ZIUjExdjXgKzFAQu9QE2ZLHOUF2UTGCKZYVh631vhyyBRPwQUBPslvYoh5D9XBk/Zq0G8YignHsHR+GJ68VlEVkwxLabN1CYspmETJHduCkuUUkVBkqztFzX6Z696H0lail2VpT7Isl6aQjB0Zll3flTceAnAfvjUl0kaFFLrrqgzGRUqc4Vby7O8gWNedhz/5bYLZvLGbYr2wS2/AVYl3dVBdDVjg2ZOYRE+V5d63BJbHDpEBF81ATmd6FuOtphCDU8X8RFiSs7e2MHTaLIFNXD4DzReQj8c4s3ZG8lNoFzkqibZAoJZ3R3SVV+O+GvJVuN1GQhKJhXd0d7chiwuFJff9tQbqeX0+jedSXSr9t+G4FSoAQEiV+S2LZEB583sz+w3GoUIkUxAx0zT7W13EJ5ZOqLI+zCfDhOpkYi6xn/A6lIFFa2Q30oWgv7pg=
  app: pickems-fb
  on:
    repo: kcin1018/pickems-api
